version: "2"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_CREATE_TOPICS: "tweets:1:1,filtered-tweets:1:1"
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  tweets-consumer:
    image: tweets-consumer
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092

  tweets-filtering:
    image: tweets-filtering
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092

  filtered-tweets-consumer:
    image: filtered-tweets-consumer
    ports:
      - 8080:8080
    depends_on:
        - kafka
    environment:
        KAFKA_BOOTSTRAP_SERVER: kafka:9092
